# Generated by Django 4.0.dev20210212083948 on 2021-02-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_secret_key', models.CharField(max_length=225)),
                ('text_public_key', models.CharField(max_length=225)),
                ('live_public_key', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=255)),
                ('no_rooms', models.IntegerField(verbose_name=10)),
                ('no_bath', models.IntegerField(verbose_name=10)),
                ('property_desc', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=100)),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_Id', models.CharField(max_length=50)),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties')),
            ],
        ),
    ]
