# Generated by Django 3.1.6 on 2021-03-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_lease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_title',
            field=models.CharField(max_length=60),
        ),
    ]
