# Generated by Django 3.1.6 on 2021-03-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210316_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='lease_options',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_lease',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Lease', 'Lease')], default='oak', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('1', 'Apartment'), ('2', 'Land'), ('3', 'Full House'), ('4', 'Office Space')], max_length=15),
        ),
        migrations.AlterField(
            model_name='propertydescription',
            name='images',
            field=models.ImageField(blank=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='propertydescription',
            name='no_of_baths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propertydescription',
            name='no_of_rooms',
            field=models.IntegerField(),
        ),
    ]
